### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by inancgumus** [aditya43/clear-shell-screen-golang#1]
Hi,

You're violating the license of my screen package by showing the code as if it's your own product. Please remove the repository or change the license and add my name as in here: https://github.com/inancgumus/screen/blob/master/LICENSE.

Thank you.
Inanc Gumus

**Comment by aditya43** [comment]
Hello,

I have added your name.
I setup that repo for learning purposes only.
Thank you for excellent package.
---------------------------------------
Regards
AdiInviter Pro Support| www.adiinviter.com
Pune, India 411046

**Comment by inancgumus** [comment]
Got it, no problem! Thanks.
